version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/web
        environment:
            - PORT:5000
            - TOKEN:818567325:AAFEslaERE6_x8xfR1OW1MaWa-7HRStQuDk
            - CHATID:356316908